spring.application.name=Sistema de Integracao WIPO - Daniel Law

# === DATASOURCE (PostgreSQL) ===
spring.datasource.url=jdbc:postgresql://localhost:5433/DanielLaw
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / HIBERNATE ===
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# === VIEWS ===
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp